[package]
name = "k8s-ide-desktop"
version = "0.0.1"
description = "K8s IDE desktop shell"
authors = ["k8s-ide"]
edition = "2021"

[lib]
name = "k8s_ide_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
